version: '3'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    depends_on:
      - db
    env_file:
      - .env
    command: sh -c "npm run migrate && npm start"

  db:
    image: postgres:latest
    env_file:
      - .env
    ports:
      - 5432:5432
